title = "Policy Search with Physics Prior"

max_iter = 10
seed = 1

mass = [0.5, 0.5]
length = [0.25, 0.25]
x_dim = 4
u_dim = 1
dt = 0.01
max_torque = 2.0

T = 10
M = 5
N = 7

[dyna_prior]
#MLP
input_mat = [[0.0], [1.0]]
hidden_size = 128
layer_depths = 2
act = "softplus"

angular_dims = [0, 1]
lr = 0.001

#dynamics epoch per global gps iteration
epoch =10 #1
batch_size = 100

[global_policy]
angular_dims = [0]
epoch_per_iteration=15
batch_size=100
layer_depth=3
hidden_size=64
act="softplus"
lr = 0.001


# eta_min = 0.01
# eta_max = 1.0

# lg_step = 4