title = "Guided Policy Search with Physics Prior"
seed = 0
[prior]
#MLP
hidden_size = 64
layer_depths = 2
act = "softplus"

angular_dims = [0]
lr = 0.001

#dynamics epoch per global gps iteration
epoch = 5
batch_size = 100

[gps]
max_iter = 5
M = 3
N = 10
T = 200
